### ISSUE TITLE
Its horizontal line 

### ISSUE THREAD

**Issue by Rahulkumrr** [Rahulkumrr/Practice#2]

**Comment by Rahulkumrr** [comment]
Can anyone remove that horizontal line in **index.html**

**Comment by Rahullkumr** [comment]
Yes, just remove that **<hr>** tag inside **_

<script>

_** tag

**Comment by Rahullkumr** [comment]
Yes, just remove that **<hr>** tag inside **_<script> _** tag

**Comment by Rahullkumr** [comment]
Yes, just remove that **<hr>** tag inside **<script>** tag

**Comment by Rahullkumr** [comment]
Yes, just remove that _hr_ tag inside **_<script>_** tag

**Comment by Rahulkumrr** [comment]
Ok! Thanks for the help.
